title: KKK
author: Kandace
email: kiwdev1984@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  parctice blog site

# social links
Kandace: https://www.facebook.com/kmamachopchop
KandaceW: https://github.com/KandaceW

show_excerpts: false # set to false to remove excerpts on the homepage
